### ISSUE TITLE
Error: Cannot find type 'UnityAPI' in scope

### ISSUE THREAD

**Issue by khaneja** [DavidPeicho/unity-swiftui-example#15]
Hello! I used your blog post for Unity-SwiftUI integration, but I'm encountering an error in "UnityBridge.swift":

<img width="1840" alt="Screenshot 2023-10-17 at 2 18 05 PM" src="https://github.com/DavidPeicho/unity-swiftui-example/assets/104416665/6da28e66-8421-4d6f-9958-0436e56c6eb6">

Appreciate any help!

**Comment by DavidPeicho** [comment]
The API is created inside the Unity package, and must be visible in the xcode project. Did you follow the instruction about creating a custom [AutoBuilder](https://github.com/DavidPeicho/unity-swiftui-example/blob/main/unityapp/Assets/Editor/AutoBuilder.cs)?

**Comment by khaneja** [comment]
That solved the issue. Thanks!
