### ISSUE TITLE
Xcode complains on API.swift file included in UnityFramework

### ISSUE THREAD

**Issue by anelad** [DavidPeicho/unity-swiftui-example#17]
Hey @DavidPeicho I've read that you are not working with Swift and Unity anymore but maybe you can help me on this.

I've read your tutorial in Medium and tried to run the repo.

Xcode complains on `API.swfit` inside the unity project lying in _/Assets/Plugins/iOS_ saying it cannot find types `NativeCallsProtocol` and `TestDelegate` and does not build the project at all.

Of course I've changed the Unity (2022.3.15f) and Xcode (15.0.1) versions, maybe that's the reason; IDK yet. Maybe i miss something.

Any suggestions do you have? Thanks.

**Comment by antiero** [comment]
@anelad - probably a bit late now, but I just fixed up the Build for Unity 6 / Xcode 16.1: https://github.com/DavidPeicho/unity-swiftui-example/pull/18

**Comment by anelad** [comment]
@antiero yes, it’s a bit late for me, but I hope it will be helpful for any others. Thank you.

For me, I decided to use SceneKit instead of Unity and in my use-case, that decision was an absolute banger!
