### ISSUE TITLE
Error for UnityBridge swift file

### ISSUE THREAD

**Issue by PritishSawant** [DavidPeicho/unity-swiftui-example#2]
Hi,
 can you help me with this. I have followed all the steps of integrating unity library recommended in the repo

<img width="960" alt="Screenshot 2021-04-14 at 8 02 45 PM" src="https://user-images.githubusercontent.com/24708929/114728190-80e55f80-9d5c-11eb-9194-ac256b172753.png">

**Comment by DavidPeicho** [comment]
Hi, I believe your issue is simply that your dependencies are wrong and so the API defined in `UnityBridge` isnt visible. Did you set the header to `public`?

**Comment by PritishSawant** [comment]
Yes

**Comment by DavidPeicho** [comment]
I will need a bit more context to help here, but It definitely is a small build issue

**Comment by dandepeched** [comment]
@DavidPeicho , I have same problem when trying to use your files in my own project. Your project is working perfect, but when I took UnityBridge.swift and NativeCallProxy-Bridging-Header.h for my project, it now cannot be builded. I'm using same unity sample project and files dependencies are the same in it. My project is just swift, without swiftui.
![Screenshot 2021-06-07 at 09 18 53](https://user-images.githubusercontent.com/5269832/120968669-d002ac00-c771-11eb-9672-c45b260f87b1.png)
![Screenshot 2021-06-07 at 09 21 00](https://user-images.githubusercontent.com/5269832/120968680-d3963300-c771-11eb-9a0b-1b62d29c73ae.png)
![Screenshot 2021-06-07 at 09 19 52](https://user-images.githubusercontent.com/5269832/120968690-d7c25080-c771-11eb-9ddb-4de0256e2be7.png)
![Screenshot 2021-06-07 at 09 19 05](https://user-images.githubusercontent.com/5269832/120968694-dabd4100-c771-11eb-98df-91735a09a219.png)

**Comment by DavidPeicho** [comment]
Hey @dandepeched, you need to set the NativeCallProxy.h as a bridging header. It's an ObjectiveC file, and the swift need some info about that. Please have a look at the [Apple documentation](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift)

**Comment by dandepeched** [comment]
Yes, I was missing path to the NativeCallProxy-Bridging-Header.h in the Build Settings/Objective-С Bridging Header.
Now I can build the project. Thanks for your help!
