### ISSUE TITLE
Not working in Unity 20.3.24

### ISSUE THREAD

**Issue by JakobWitsch** [DavidPeicho/unity-swiftui-example#5]
Hello!

Thank you for your great example on how to integrate Unity into Swift!

I have a project running in Unity 20.3.18 and it works perfect however it does not do well in 20.3.24.
The problem is, that the Smash Screen is shown and causes a timing error I think. Would be great if you take a look at it as I am dependent on this solution and not able to fix it by myself as I am quite new to Swift.

Thank you 
Jakob

**Comment by DavidPeicho** [comment]
I don't understand what doesn't work exactly?

**Comment by DavidPeicho** [comment]
Any news on that? Can I close it?

**Comment by JakobWitsch** [comment]
Yes you can close it. Thank you
